### ISSUE TITLE
Cannot download the 0.02 version

### ISSUE THREAD

**Issue by Lwaht** [Chrono-Heritage/Moderndustry#3]
![Screenshot_20240604_181655_Mindustry](https://github.com/Chrono-Heritage/Moderndustry/assets/128390812/0dcd8569-1e5c-4c32-bdbc-456e3e9f9c69)

**Comment by traincrisis** [comment]
hmm

**Comment by Chrono-Heritage** [comment]
Well, this mod a java mod, it cannot run on mobile. You can only play this mod in computer. If you want to play this mod, you may use Nucleardustry and Metaldustry mod, this mod's contents are in these mods.
